// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwtsadggupulursshdvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3dHNhZGdndXB1bHVyc3NoZHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDY0NDMsImV4cCI6MjA2NjMyMjQ0M30.3vwO5_HPnodxv9Uh0VimBfhiJktZ9NimjgF2VV2ViFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);